<a href="https://colab.research.google.com/github/ShyamBhagat2004/amazon-sentiment-review/blob/main/Shyam_Bhagat_Amazon_Product_Review_(Github).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from datetime import datetime
import csv

In [ ]:
data = pd.read_csv('amazon_train.csv')


In [ ]:
data.head()

overall  verified   reviewTime                        reviewerID  \
0        1     False  11 12, 2016  C413C78E10E54C5DB41837889F36C1E8   
1        1      True   12 6, 2016  490AE37808EFEE3AF4FE6DEBDEB5A4C8   
2        1      True  09 17, 2014  74A9FA5A64449BEE2A2E8E3F62872F0F   
3        1      True  06 11, 2016  EB561158A2829D98B467FE03CC1E45F1   
4        1      True  12 23, 2017  5045D801332850D21618DD13A697CD9B   

                               asin                      reviewerName  \
0  565D194F38B1CC3F806EE677C61F639C  465E154EC79AFFAB5EB2607198B21433   
1  0D66512A0A7F580523AB996378DF0F14  760C63E8E5E8DC3FAA01878D37BA5678   
2  A0E45600FF2C5A779CB4314F379C253A  C6E4DD5C1C4EC09E90182644ED6CA9EF   
3  37AB9A82470595E0ACB88BAC48C150EE  F4892A77EA45C52F40AB17ED537EF9FF   
4  5772FF30428EEB8E0258C1A53CA2EC50  522F0BBFF2B47F1D63FF781A0AB1D079   

                                          reviewText  \
0      all of the reviews for this product are fake.   
1                             wrong part. our fault.   
2                   this wire set it really sucks!!!   
3  first use, it leaked instantly. even at 5 buck...   
4                                         didn't fit   

                     summary  unixReviewTime  vote image  \
0  All fake reviews, beware.      1478908800   2.0   NaN   
1                   One Star      1480982400   NaN   NaN   
2                   One Star      1410912000   NaN   NaN   
3                   One Star      1465603200   NaN   NaN   
4                   One Star      1513987200   NaN   NaN   

                                          style    category   id  
0                      {'Size:': ' Polaris H4'}  automotive  ab0  
1                                           NaN  automotive  ab1  
2                                           NaN  automotive  ab2  
3  {'Color:': ' Clear', 'Style:': ' 45 Degree'}  automotive  ab3  
4                                           NaN  automotive  ab4

In [ ]:
data = pd.read_csv('amazon_train.csv')

data = data.drop("reviewerID", axis="columns")
data = data.drop("verified", axis="columns")
data = data.drop("asin", axis="columns")
data = data.drop("reviewerName", axis="columns")
data = data.drop("id", axis="columns")
data = data.drop("reviewTime", axis="columns")
data = data.drop("image", axis="columns")







data.head()

overall                                         reviewText  \
0        1      all of the reviews for this product are fake.   
1        1                             wrong part. our fault.   
2        1                   this wire set it really sucks!!!   
3        1  first use, it leaked instantly. even at 5 buck...   
4        1                                         didn't fit   

                     summary  unixReviewTime  vote  \
0  All fake reviews, beware.      1478908800   2.0   
1                   One Star      1480982400   NaN   
2                   One Star      1410912000   NaN   
3                   One Star      1465603200   NaN   
4                   One Star      1513987200   NaN   

                                          style    category  
0                      {'Size:': ' Polaris H4'}  automotive  
1                                           NaN  automotive  
2                                           NaN  automotive  
3  {'Color:': ' Clear', 'Style:': ' 45 Degree'}  automotive  
4                                           NaN  automotive

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#Split data into train and testing
X_train, X_test, y_train, y_test = train_test_split(data, data['overall'], test_size = 1, random_state=0, shuffle=True)


print('Full dataset shape: ', data.shape[0])
print('Train dataset shape: ', X_train.shape[0])
print('Test dataset shape: ', X_test.shape[0])

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train) #Create and train a linear model

predictions = model.predict(X_test) #Predict test subset of data


Full dataset shape:  29189
Train dataset shape:  29188
Test dataset shape:  1


ValueError: ignored

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

myVect = TfidfVectorizer()
myVect.fit(data["reviewText"].fillna('')+ ' '+data["summary"].fillna(' '))

xTest = myVect.transform(data['reviewText'].fillna('') + ' ' + data['summary'].fillna(''))
xTrain = myVect.transform(data['reviewText'].fillna('') + ' ' + data['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

NameError: ignored

In [ ]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from scipy.sparse import hstack
from sklearn.preprocessing import MinMaxScaler
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from pprint import pprint
from scipy.sparse import hstack
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer

trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")


def createFile(model, model_name, test_ids, x_test_data):
  y_sub = model.predict(x_test_data)
  submiss = pd.DataFrame({'pred':y_sub, 'id':test_ids})

  fileName = f"{model_name} Jake and Shyam1.csv"
  submiss.to_csv(fileName, index=False)
  print(fileName)

y = trainingData["overall"]


myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('')+ ' '+trainingData["summary"].fillna(' '))

xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

#Dictionary for potential hyperparameters for each model
modelsParameters = {

    'Perceptron': {
        'model': Perceptron(),
        'params': {
            'alpha': np.linspace(0.0001, 0.001, num=10),
            'max_iter': [1000, 2000, 3000],
            'penalty': [None, 'l2', 'l1', 'elasticnet']
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(solver='liblinear'),
        'params': {
            'C': np.logspace(-3, 3, num=7),
            'penalty': ['l1', 'l2']
        }
    },
    'Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=10),
            'fit_prior': [True, False]
        }
}}

for model_name, model_info in modelsParameters.items():
    print(f"now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    cfu = confusion_matrix(y_validation, y_pred)
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    roc_auc = roc_auc_score(y_validation, y_pred)
    a_s = accuracy_score(y_validation, y_pred)

    print(f"{model_name} \nConfusion Matrix")
    print(cfu)
    print(f"F1 score: {f1_s:.2f}")
    print(f"ROC AUC: {roc_auc:.2f}")
    print(f"Accuracy Score: {a_s:.2f} \n")
testingIDS = testingData["id"]

for model_name, model_info in modelsParameters.items():
    print(f"{model_name} now being made")
    trained_model = model_info['model']
    createFile(trained_model, model_name, testingIDS, xTest)

now doing Perceptron...


KeyboardInterrupt: ignored

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, f1_score, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")

def createFile(model, model_name, test_ids, x_test_data):
    y_sub = model.predict(x_test_data)
    submiss = pd.DataFrame({'pred': y_sub, 'id': test_ids})

    fileName = f"{model_name} Predictions.csv"
    submiss.to_csv(fileName, index=False)
    print(fileName)

y = trainingData["overall"]

myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('') + ' ' + trainingData["summary"].fillna(' '))

xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

# Dictionary for potential hyperparameters for each model
modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=2),
            'fit_prior': [True]
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=3000),
        'params': {
            'C': np.logspace(-3, 3, num=2),
        }
    },
    'Random Forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [200],
            'max_depth': [20],
        }
    }
}

for model_name, model_info in modelsParameters.items():
    print(f"Now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    cfu = confusion_matrix(y_validation, y_predicted)
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    a_s = accuracy_score(y_validation, y_predicted)

    print(f"{model_name} \nConfusion Matrix")
    print(cfu)
    print(f"F1 score: {f1_s:.2f}")
    print(f"Accuracy Score: {a_s:.2f} \n")

testingIDS = testingData["id"]

for model_name, model_info in modelsParameters.items():
    print(f"{model_name} now being made")
    trained_model = model_info['model']
    createFile(trained_model, model_name, testingIDS, xTest)


Now doing Multinomial Naive Bayes...
Ideal Params Multinomial Naive Bayes: {'alpha': 1.0, 'fit_prior': True}
Multinomial Naive Bayes 
Confusion Matrix
[[742 346  76  25   3]
 [219 716 191  66   6]
 [ 80 387 543 166   5]
 [ 42 210 209 627  54]
 [ 54 106  97 336 532]]
F1 score: 0.55
Accuracy Score: 0.54 

Now doing Logistic Regression...


KeyboardInterrupt: ignored

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, f1_score, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

trainingData = pd.read_csv("amazon_train.csv")


trainingData = trainingData.drop("reviewerID", axis="columns")
trainingData = trainingData.drop("verified", axis="columns")
trainingData = trainingData.drop("asin", axis="columns")
trainingData = trainingData.drop("reviewerName", axis="columns")
trainingData = trainingData.drop("id", axis="columns")
trainingData = trainingData.drop("reviewTime", axis="columns")
trainingData = trainingData.drop("image", axis="columns")

testingData = pd.read_csv("amazon_test.csv")




def createFile(model, model_name, test_ids, x_test_data):
    y_sub = model.predict(x_test_data)
    submiss = pd.DataFrame({'pred': y_sub, 'id': test_ids})

    fileName = f"{model_name} Predictions.csv"
    submiss.to_csv(fileName, index=False)
    print(fileName)

y = trainingData["overall"]

myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('') + ' ' + trainingData["summary"].fillna(' '))

xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)
# Add other necessary imports as needed

# ... (your existing code)

modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=2),
            'fit_prior': [True]
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=3000),
        'params': {
            'C': np.logspace(-3, 3, num=2),
        }
    },
    'Random Forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [200],
            'max_depth': [20],
        }
    }
}

modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=2),
            'fit_prior': [True]
        }
    },

    'Random Forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [200],
            'max_depth': [20],
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=3000),
        'params': {
            'C': np.logspace(-3, 3, num=2),
        }
    }

}

for model_name, model_info in modelsParameters.items():
    print(f"Now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    cfu = confusion_matrix(y_validation, y_predicted)
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    a_s = accuracy_score(y_validation, y_predicted)

    print(f"{model_name} \nConfusion Matrix")
    print(cfu)
    print(f"F1 score: {f1_s:.2f}")
    print(f"Accuracy Score: {a_s:.2f}")

    if f1_s >= 0.62:
        print(f"Baseline F1-score achieved for {model_name}!")
        createFile(trained_model, model_name, testingIDS, xTest)
        break  # Stop the loop if baseline is achieved
    else:
        print("Baseline F1-score not achieved. Trying next model.")


Now doing Multinomial Naive Bayes...
Ideal Params Multinomial Naive Bayes: {'alpha': 1.0, 'fit_prior': True}
Multinomial Naive Bayes 
Confusion Matrix
[[742 346  76  25   3]
 [219 716 191  66   6]
 [ 80 387 543 166   5]
 [ 42 210 209 627  54]
 [ 54 106  97 336 532]]
F1 score: 0.55
Accuracy Score: 0.54
Baseline F1-score not achieved. Trying next model.
Now doing Random Forest...
Ideal Params Random Forest: {'max_depth': 20, 'n_estimators': 200}
Random Forest 
Confusion Matrix
[[886 178  49  29  50]
 [385 474 175  90  74]
 [160 251 518 149 103]
 [ 79 111 186 539 227]
 [ 80  56  60 174 755]]
F1 score: 0.54
Accuracy Score: 0.54
Baseline F1-score not achieved. Trying next model.
Now doing Logistic Regression...
Ideal Params Logistic Regression: {'C': 1000.0}
Logistic Regression 
Confusion Matrix
[[721 276 111  44  40]
 [267 514 248 108  61]
 [110 264 509 218  80]
 [ 53 128 221 537 203]
 [ 43  63  82 233 704]]
F1 score: 0.51
Accuracy Score: 0.51
Baseline F1-score not achieved. Trying next mo

In [ ]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from scipy.sparse import hstack
from sklearn.preprocessing import MinMaxScaler
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from pprint import pprint
from scipy.sparse import hstack
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")

def score_of_sentiment(overall):
  return 0 if overall < 4 else 1

def createFile(model, model_name, test_ids, x_test_data):
  y_sub = model.predict(x_test_data)
  submiss = pd.DataFrame({'pred':y_sub, 'id':test_ids})
  submiss = pd.DataFrame({'id':test_ids, 'pred':y_sub})


  fileName = f"{model_name} Jake and Shyam Part 4.csv"
  submiss.to_csv(fileName, index=False)
  print(fileName)

y = trainingData["overall"].apply(score_of_sentiment)

myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('')+ ' '+trainingData["summary"].fillna(' '))

xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

#Dictionary for potential hyperparameters for each model
modelsParameters = {

    'Perceptron': {
        'model': Perceptron(),
        'params': {
            'alpha': np.linspace(0.0001, 0.001, num=10),
            'max_iter': [1000, 2000, 3000],
            'penalty': [None, 'l2', 'l1', 'elasticnet']
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(solver='liblinear'),
        'params': {
            'C': np.logspace(-3, 3, num=7),
            'penalty': ['l1', 'l2']
        }
    },
    'Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=10),
            'fit_prior': [True, False]
        }
}}

modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=2),
            'fit_prior': [True]
        }
    },

    'Random Forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [200],
            'max_depth': [20],
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=3000),
        'params': {
            'C': np.logspace(-3, 3, num=2),
        }
    }

}
for model_name, model_info in modelsParameters.items():
    print(f"now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    cfu = confusion_matrix(y_validation, y_predicted)
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    roc_auc = roc_auc_score(y_validation, y_predicted)
    a_s = accuracy_score(y_validation, y_predicted)

    print(f"{model_name} \nConfusion Matrix")
    print(cfu)
    print(f"F1 score: {f1_s:.2f}")
    print(f"ROC AUC: {roc_auc:.2f}")
    print(f"Accuracy Score: {a_s:.2f} \n")
testingIDS = testingData["id"]

for model_name, model_info in modelsParameters.items():
    print(f"{model_name} now being made")
    trained_model = model_info['model']
    createFile(trained_model, model_name, testingIDS, xTest)

now doing Multinomial Naive Bayes...
Ideal Params Multinomial Naive Bayes: {'alpha': 0.1, 'fit_prior': True}
Multinomial Naive Bayes 
Confusion Matrix
[[3342  229]
 [ 877 1390]]
F1 score: 0.79
ROC AUC: 0.77
Accuracy Score: 0.81 

now doing Random Forest...
Ideal Params Random Forest: {'max_depth': 20, 'n_estimators': 200}
Random Forest 
Confusion Matrix
[[3569    2]
 [1832  435]]
F1 score: 0.56
ROC AUC: 0.60
Accuracy Score: 0.69 

now doing Logistic Regression...
Ideal Params Logistic Regression: {'C': 1000.0}
Logistic Regression 
Confusion Matrix
[[3013  558]
 [ 581 1686]]
F1 score: 0.79
ROC AUC: 0.79
Accuracy Score: 0.80 

Multinomial Naive Bayes now being made
Multinomial Naive Bayes Jake and Shyam Part 4.csv
Random Forest now being made
Random Forest Jake and Shyam Part 4.csv
Logistic Regression now being made
Logistic Regression Jake and Shyam Part 4.csv


In [ ]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from scipy.sparse import hstack
from sklearn.preprocessing import MinMaxScaler
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from pprint import pprint
from scipy.sparse import hstack
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")

def score_of_sentiment(overall):
  return 0 if overall < 4 else 1

def createFile(model, model_name, test_ids, x_test_data):
  y_sub_prob = model.predict_proba(x_test_data)[:, 1]
  y_sub = model.predict(x_test_data)
  submiss = pd.DataFrame({'pred':y_sub, 'id':test_ids})
  submiss = pd.DataFrame({'id':test_ids, 'pred':y_sub_prob})


  fileName = f"{model_name} Jake and Shyam Part 4.csv"
  submiss.to_csv(fileName, index=False)
  print(fileName)

y = trainingData["overall"].apply(score_of_sentiment)

myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('')+ ' '+trainingData["summary"].fillna(' '))

xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

#Dictionary for potential hyperparameters for each model
modelsParameters = {

    'Perceptron': {
        'model': Perceptron(),
        'params': {
            'alpha': np.linspace(0.0001, 0.001, num=10),
            'max_iter': [1000, 2000, 3000],
            'penalty': [None, 'l2', 'l1', 'elasticnet']
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(solver='liblinear'),
        'params': {
            'C': np.logspace(-3, 3, num=7),
            'penalty': ['l1', 'l2']
        }
    },
    'Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=10),
            'fit_prior': [True, False]
        }
}}

modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=2),
            'fit_prior': [True]
        }
    },

    'Random Forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [200],
            'max_depth': [20],
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=3000),
        'params': {
            'C': np.logspace(-3, 3, num=2),
        }
    }

}
for model_name, model_info in modelsParameters.items():
    print(f"now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    cfu = confusion_matrix(y_validation, y_predicted)
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    roc_auc = roc_auc_score(y_validation, y_predicted)
    a_s = accuracy_score(y_validation, y_predicted)

    print(f"{model_name} \nConfusion Matrix")
    print(cfu)
    print(f"F1 score: {f1_s:.2f}")
    print(f"ROC AUC: {roc_auc:.2f}")
    print(f"Accuracy Score: {a_s:.2f} \n")
testingIDS = testingData["id"]

for model_name, model_info in modelsParameters.items():
    print(f"{model_name} now being made")
    trained_model = model_info['model']
    createFile(trained_model, model_name, testingIDS, xTest)

now doing Multinomial Naive Bayes...
Ideal Params Multinomial Naive Bayes: {'alpha': 0.1, 'fit_prior': True}
Multinomial Naive Bayes 
Confusion Matrix
[[3342  229]
 [ 877 1390]]
F1 score: 0.79
ROC AUC: 0.77
Accuracy Score: 0.81 

now doing Random Forest...
Ideal Params Random Forest: {'max_depth': 20, 'n_estimators': 200}
Random Forest 
Confusion Matrix
[[3566    5]
 [1834  433]]
F1 score: 0.56
ROC AUC: 0.59
Accuracy Score: 0.68 

now doing Logistic Regression...
Ideal Params Logistic Regression: {'C': 1000.0}
Logistic Regression 
Confusion Matrix
[[3013  558]
 [ 581 1686]]
F1 score: 0.79
ROC AUC: 0.79
Accuracy Score: 0.80 

Multinomial Naive Bayes now being made
Multinomial Naive Bayes Jake and Shyam Part 4.csv
Random Forest now being made
Random Forest Jake and Shyam Part 4.csv
Logistic Regression now being made
Logistic Regression Jake and Shyam Part 4.csv


In [ ]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from scipy.sparse import hstack
from sklearn.preprocessing import MinMaxScaler
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from pprint import pprint
from scipy.sparse import hstack
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")

def score_of_sentiment(overall):
  return 0 if overall < 4 else 1

def createFile(model, model_name, test_ids, x_test_data):
    y_sub_prob = model.predict_proba(x_test_data)

    # Create a DataFrame with separate columns for each class
    submiss = pd.DataFrame(data=y_sub_prob, columns=[f'pred_class_{i}' for i in range(1, 6)])

    # Add the 'id' column to the DataFrame
    submiss['id'] = test_ids

    # Save the DataFrame to a CSV file
    fileName = f"{model_name} Jake and Shyam Part 66.csv"
    submiss.to_csv(fileName, index=False)
    print(fileName)


y = trainingData["overall"].apply(score_of_sentiment)

myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('')+ ' '+trainingData["summary"].fillna(' '))

xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

#Dictionary for potential hyperparameters for each model
modelsParameters = {

    'Perceptron': {
        'model': Perceptron(),
        'params': {
            'alpha': np.linspace(0.0001, 0.001, num=10),
            'max_iter': [1000, 2000, 3000],
            'penalty': [None, 'l2', 'l1', 'elasticnet']
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(solver='liblinear'),
        'params': {
            'C': np.logspace(-3, 3, num=7),
            'penalty': ['l1', 'l2']
        }
    },
    'Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=10),
            'fit_prior': [True, False]
        }
}}

modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=2),
            'fit_prior': [True]
        }
    },

    'Random Forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [200],
            'max_depth': [20],
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=5),
        'params': {
            'C': np.logspace(-3, 3, num=2),
        }
    }

}
for model_name, model_info in modelsParameters.items():
    print(f"now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    cfu = confusion_matrix(y_validation, y_predicted)
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    roc_auc = roc_auc_score(y_validation, y_predicted)
    a_s = accuracy_score(y_validation, y_predicted)

    print(f"{model_name} \nConfusion Matrix")
    print(cfu)
    print(f"F1 score: {f1_s:.2f}")
    print(f"ROC AUC: {roc_auc:.2f}")
    print(f"Accuracy Score: {a_s:.2f} \n")
testingIDS = testingData["id"]

for model_name, model_info in modelsParameters.items():
    print(f"{model_name} now being made")
    trained_model = model_info['model']
    createFile(trained_model, model_name, testingIDS, xTest)

now doing Multinomial Naive Bayes...
Ideal Params Multinomial Naive Bayes: {'alpha': 0.1, 'fit_prior': True}
Multinomial Naive Bayes 
Confusion Matrix
[[3342  229]
 [ 877 1390]]
F1 score: 0.79
ROC AUC: 0.77
Accuracy Score: 0.81 

now doing Random Forest...
Ideal Params Random Forest: {'max_depth': 20, 'n_estimators': 200}
Random Forest 
Confusion Matrix
[[3569    2]
 [1789  478]]
F1 score: 0.57
ROC AUC: 0.61
Accuracy Score: 0.69 

now doing Logistic Regression...


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://sciki

Ideal Params Logistic Regression: {'C': 1000.0}


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression 
Confusion Matrix
[[3326  245]
 [ 684 1583]]
F1 score: 0.83
ROC AUC: 0.81
Accuracy Score: 0.84 

Multinomial Naive Bayes now being made


ValueError: ignored

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, f1_score, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")

def createFile(model, model_name, test_ids, x_test_data):
    y_sub = model.predict(x_test_data)
    submiss = pd.DataFrame({'pred': y_sub, 'id': test_ids})

    fileName = f"{model_name} Predictions.csv"
    submiss.to_csv(fileName, index=False)
    print(fileName)

y = trainingData["overall"]

myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('') + ' ' + trainingData["summary"].fillna(' '))

xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

# Dictionary for potential hyperparameters for each model
modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.1, 0.5, 1.0],
            'fit_prior': [True]
        }
    },
    'Logistic Regression': {
        'model': LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=3000),
        'params': {
            'C': np.logspace(-3, 3, num=2),
        }
    },
    'Random Forest': {
        'model': RandomForestClassifier(n_estimators=200, class_weight='balanced'),
        'params': {
            'max_depth': [20],
        }
    }
}

for model_name, model_info in modelsParameters.items():
    print(f"Now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    cfu = confusion_matrix(y_validation, y_predicted)
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    a_s = accuracy_score(y_validation, y_predicted)

    print(f"{model_name} \nConfusion Matrix")
    print(cfu)
    print(f"F1 score: {f1_s:.2f}")
    print(f"Accuracy Score: {a_s:.2f} \n")

testingIDS = testingData["id"]

for model_name, model_info in modelsParameters.items():
    print(f"{model_name} now being made")
    trained_model = model_info['model']
    createFile(trained_model, model_name, testingIDS, xTest)


FileNotFoundError: ignored

In [ ]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, f1_score, accuracy_score, roc_auc_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

# Load data
trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")

# Define target variable
y = trainingData["overall"]

# Create TF-IDF vectorizer
myVect = TfidfVectorizer()
myVect.fit(trainingData["reviewText"].fillna('') + ' ' + trainingData["summary"].fillna(''))

# Transform data
xTest = myVect.transform(testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna(''))
xTrain = myVect.transform(trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna(''))

# Split data
x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain, y, test_size=0.2, random_state=9)

# Dictionary for potential hyperparameters for each model
modelsParameters = {
    'Multinomial Naive Bayes': {
        'model': MultinomialNB(),
        'params': {
            'alpha': np.linspace(0.1, 1.0, num=2),
            'fit_prior': [True]
        },
    },
    'Random Forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [200],
            'max_depth': [20],
        }
    }
}

# Function to create predictions file
def createFile(model, model_name, test_ids, x_test_data):
    y_sub = model.predict(x_test_data)
    submiss = pd.DataFrame({'pred': y_sub, 'id': test_ids})
    fileName = f"{model_name} Predictions.csv"
    submiss.to_csv(fileName, index=False)
    print(fileName)

# Loop through models
for model_name, model_info in modelsParameters.items():
    print(f"Now doing {model_name}...")
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring="f1_macro")
    grid_search.fit(x_train_split, y_train_split)

    bestParams = grid_search.best_params_
    print(f"Ideal Params {model_name}: {bestParams}")

    trained_model = model_info['model'].set_params(**bestParams)
    trained_model.fit(x_train_split, y_train_split)
    y_predicted = trained_model.predict(x_validation)

    # Confusion Matrix
    cfu = confusion_matrix(y_validation, y_predicted)
    print(f"{model_name} \nConfusion Matrix:")
    print(cfu)

    # F1 score
    f1_s = f1_score(y_validation, y_predicted, average="macro")
    print(f"F1 score: {f1_s:.2f}")

    # Accuracy Score
    a_s = accuracy_score(y_validation, y_predicted)
    print(f"Accuracy Score: {a_s:.2f}")

    # ROC-AUC Score (for each class against the rest)
    y_proba = trained_model.predict_proba(x_validation)
    roc_auc_scores = []
    for i in range(len(trained_model.classes_)):
        roc_auc_i = roc_auc_score((y_validation == trained_model.classes_[i]).astype(int), y_proba[:, i])
        roc_auc_scores.append(roc_auc_i)
        print(f"ROC-AUC Score (Class {trained_model.classes_[i]}): {roc_auc_i:.2f}")

    print("\n")

# Create predictions for each model
testingIDS = testingData["id"]
for model_name, model_info in modelsParameters.items():
    print(f"{model_name} now being made")
    trained_model = model_info['model']
    createFile(trained_model, model_name, testingIDS, xTest)



In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import VotingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, accuracy_score
from sklearn.metrics import confusion_matrix
# Load data
trainingData = pd.read_csv("amazon_train.csv")
testingData = pd.read_csv("amazon_test.csv")

# Combine 'reviewText' and 'summary'
trainingData['text_combined'] = trainingData['reviewText'].fillna('') + ' ' + trainingData['summary'].fillna('')
testingData['text_combined'] = testingData['reviewText'].fillna('') + ' ' + testingData['summary'].fillna('')

# Vectorize 'text_combined'
tfidf_vectorizer = TfidfVectorizer()
xTrain_tfidf = tfidf_vectorizer.fit_transform(trainingData['text_combined'])
xTest_tfidf = tfidf_vectorizer.transform(testingData['text_combined'])

# Split the data
y = trainingData["overall"]
x_train_split, x_validation, y_train_split, y_validation = train_test_split(xTrain_tfidf, y, test_size=0.10, random_state=9)


# Define classifiers
classifier1 = MultinomialNB(alpha=1.67, fit_prior=True)
classifier2 = RandomForestClassifier(n_estimators=300, class_weight="balanced", max_depth=20)
classifier3 = LogisticRegression(max_iter=3000, multi_class='multinomial', solver='lbfgs')


# Create an ensemble of classifiers
ensemble_classifier = VotingClassifier(estimators=[
    ('nb', classifier1),
    ('rf', classifier2),
    ('lr', classifier3)
], voting='soft', weights=[1, 2, 1])

# Train the ensemble classifier
ensemble_classifier.fit(x_train_split, y_train_split)

# Make predictions on the validation set
y_predicted = ensemble_classifier.predict(x_validation)

# Evaluate the model
cfu = confusion_matrix(y_validation, y_predicted)
f1_s = f1_score(y_validation, y_predicted, average="macro")
a_s = accuracy_score(y_validation, y_predicted)

print("Ensemble Classifier \nConfusion Matrix")
print(cfu)
print(f"F1 score: {f1_s:.3f}")
print(f"Accuracy Score: {a_s:.3f}")

# Make predictions on the test set
y_test_predicted = ensemble_classifier.predict(xTest_tfidf)

# Create submission file
submission = pd.DataFrame({'pred': y_test_predicted, 'id': testingData["id"]})
submission.to_csv("Ensemble_Predictions.csv", index=False)
print("Ensemble Classifier predictions on the test set saved to 'Ensemble_Predictions.csv'")
